[project]
name = "flask-zz"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.0.3",
    "httpx>=0.27.2",
    "pytest>=8.3.3",
]
